// GENERATED by web/scripts/export_lab_data.py - do not hand-edit.
// Every number here comes from the committed dataset (seed 42).
export const LAB = {
  "generatedFrom": "data/burnin_wide.csv (seed 42) via src/features.py",
  "headline": {
    "parts": 2100,
    "lots": 6,
    "latentDefects": 174,
    "defectRate": 0.0829,
    "latentPassingDatasheet": 1.0,
    "readPoints": [
      0,
      24,
      96,
      168
    ]
  },
  "hero": {
    "serial": "L04-0348",
    "lot": "L04",
    "wafer": "W01",
    "param": "Iddq_uA",
    "unit": "uA",
    "usl": 50.0,
    "hours": [
      0,
      24,
      96,
      168
    ],
    "trace": [
      21.937,
      24.476,
      37.137,
      49.452
    ],
    "value168": 49.45,
    "lotMedian168": 13.64,
    "lotSigma168": 4.223,
    "lotN": 350,
    "uslFrac": 0.989,
    "marginLeft": 0.55,
    "p05": [
      8.041,
      8.374,
      8.377,
      8.547
    ],
    "p50": [
      12.551,
      12.691,
      13.286,
      13.639
    ],
    "p95": [
      19.85,
      20.591,
      25.119,
      39.572
    ],
    "driftZ": 18.65,
    "levelZ": 4.04,
    "l2": 18.65,
    "l3": 348.5,
    "forecast168": 19.24,
    "slopeRatio": 0.36,
    "riskScore": 78.9,
    "verdict": "REJECT",
    "subScores": {
      "static_margin": 98.0,
      "dynamic_outlier": 100.0,
      "predicted_drift": 35.7,
      "multivariate": 100.0,
      "curvature": 23.2
    },
    "staticVerdict": "PASS",
    "codes": [
      {
        "code": "R-401",
        "severity": "medium",
        "message": "No single parameter trips its own limit, but the combined drift evidence across parameters is 348.5 against a 18.5 threshold (Iddq_uA 18.7 sigma, Ileak_nA 0.7 sigma). Individually ordinary, jointly rare for this lot."
      }
    ],
    "lotHist": [
      {
        "x": 0.0,
        "n": 0
      },
      {
        "x": 1.25,
        "n": 0
      },
      {
        "x": 2.5,
        "n": 0
      },
      {
        "x": 3.75,
        "n": 0
      },
      {
        "x": 5.0,
        "n": 1
      },
      {
        "x": 6.25,
        "n": 6
      },
      {
        "x": 7.5,
        "n": 15
      },
      {
        "x": 8.75,
        "n": 35
      },
      {
        "x": 10.0,
        "n": 34
      },
      {
        "x": 11.25,
        "n": 40
      },
      {
        "x": 12.5,
        "n": 46
      },
      {
        "x": 13.75,
        "n": 35
      },
      {
        "x": 15.0,
        "n": 31
      },
      {
        "x": 16.25,
        "n": 23
      },
      {
        "x": 17.5,
        "n": 13
      },
      {
        "x": 18.75,
        "n": 21
      },
      {
        "x": 20.0,
        "n": 11
      },
      {
        "x": 21.25,
        "n": 3
      },
      {
        "x": 22.5,
        "n": 6
      },
      {
        "x": 23.75,
        "n": 4
      },
      {
        "x": 25.0,
        "n": 1
      },
      {
        "x": 26.25,
        "n": 1
      },
      {
        "x": 27.5,
        "n": 2
      },
      {
        "x": 28.75,
        "n": 1
      },
      {
        "x": 30.0,
        "n": 0
      },
      {
        "x": 31.25,
        "n": 0
      },
      {
        "x": 32.5,
        "n": 1
      },
      {
        "x": 33.75,
        "n": 0
      },
      {
        "x": 35.0,
        "n": 0
      },
      {
        "x": 36.25,
        "n": 1
      },
      {
        "x": 37.5,
        "n": 0
      },
      {
        "x": 38.75,
        "n": 2
      },
      {
        "x": 40.0,
        "n": 0
      },
      {
        "x": 41.25,
        "n": 1
      },
      {
        "x": 42.5,
        "n": 2
      },
      {
        "x": 43.75,
        "n": 0
      },
      {
        "x": 45.0,
        "n": 0
      },
      {
        "x": 46.25,
        "n": 0
      },
      {
        "x": 47.5,
        "n": 1
      },
      {
        "x": 48.75,
        "n": 1
      },
      {
        "x": 50.0,
        "n": 0
      },
      {
        "x": 51.25,
        "n": 0
      },
      {
        "x": 52.5,
        "n": 2
      },
      {
        "x": 53.75,
        "n": 1
      }
    ],
    "lotDefectHist": [
      {
        "x": 0.0,
        "n": 0
      },
      {
        "x": 1.25,
        "n": 0
      },
      {
        "x": 2.5,
        "n": 0
      },
      {
        "x": 3.75,
        "n": 0
      },
      {
        "x": 5.0,
        "n": 1
      },
      {
        "x": 6.25,
        "n": 1
      },
      {
        "x": 7.5,
        "n": 2
      },
      {
        "x": 8.75,
        "n": 5
      },
      {
        "x": 10.0,
        "n": 4
      },
      {
        "x": 11.25,
        "n": 5
      },
      {
        "x": 12.5,
        "n": 7
      },
      {
        "x": 13.75,
        "n": 7
      },
      {
        "x": 15.0,
        "n": 8
      },
      {
        "x": 16.25,
        "n": 4
      },
      {
        "x": 17.5,
        "n": 5
      },
      {
        "x": 18.75,
        "n": 6
      },
      {
        "x": 20.0,
        "n": 2
      },
      {
        "x": 21.25,
        "n": 0
      },
      {
        "x": 22.5,
        "n": 2
      },
      {
        "x": 23.75,
        "n": 2
      },
      {
        "x": 25.0,
        "n": 1
      },
      {
        "x": 26.25,
        "n": 0
      },
      {
        "x": 27.5,
        "n": 0
      },
      {
        "x": 28.75,
        "n": 0
      },
      {
        "x": 30.0,
        "n": 0
      },
      {
        "x": 31.25,
        "n": 0
      },
      {
        "x": 32.5,
        "n": 0
      },
      {
        "x": 33.75,
        "n": 0
      },
      {
        "x": 35.0,
        "n": 0
      },
      {
        "x": 36.25,
        "n": 1
      },
      {
        "x": 37.5,
        "n": 0
      },
      {
        "x": 38.75,
        "n": 1
      },
      {
        "x": 40.0,
        "n": 0
      },
      {
        "x": 41.25,
        "n": 0
      },
      {
        "x": 42.5,
        "n": 0
      },
      {
        "x": 43.75,
        "n": 0
      },
      {
        "x": 45.0,
        "n": 0
      },
      {
        "x": 46.25,
        "n": 0
      },
      {
        "x": 47.5,
        "n": 0
      },
      {
        "x": 48.75,
        "n": 1
      },
      {
        "x": 50.0,
        "n": 0
      },
      {
        "x": 51.25,
        "n": 0
      },
      {
        "x": 52.5,
        "n": 0
      },
      {
        "x": 53.75,
        "n": 0
      }
    ],
    "histLo": 0.0,
    "histHi": 55.0
  },
  "compare": {
    "lot": "L01",
    "param": "Iddq_uA",
    "n": 350,
    "nDefect": 25,
    "static": {
      "unit": "uA",
      "limit": 50.0,
      "lo": 0.0,
      "hi": 50.0,
      "healthy": [
        {
          "x": 0.0,
          "n": 0
        },
        {
          "x": 2.0,
          "n": 0
        },
        {
          "x": 4.0,
          "n": 0
        },
        {
          "x": 6.0,
          "n": 17
        },
        {
          "x": 8.0,
          "n": 85
        },
        {
          "x": 10.0,
          "n": 142
        },
        {
          "x": 12.0,
          "n": 58
        },
        {
          "x": 14.0,
          "n": 12
        },
        {
          "x": 16.0,
          "n": 0
        },
        {
          "x": 18.0,
          "n": 1
        },
        {
          "x": 20.0,
          "n": 0
        },
        {
          "x": 22.0,
          "n": 0
        },
        {
          "x": 24.0,
          "n": 0
        },
        {
          "x": 26.0,
          "n": 0
        },
        {
          "x": 28.0,
          "n": 0
        },
        {
          "x": 30.0,
          "n": 0
        },
        {
          "x": 32.0,
          "n": 0
        },
        {
          "x": 34.0,
          "n": 0
        },
        {
          "x": 36.0,
          "n": 1
        },
        {
          "x": 38.0,
          "n": 0
        },
        {
          "x": 40.0,
          "n": 0
        },
        {
          "x": 42.0,
          "n": 0
        },
        {
          "x": 44.0,
          "n": 0
        },
        {
          "x": 46.0,
          "n": 0
        },
        {
          "x": 48.0,
          "n": 0
        }
      ],
      "defect": [
        {
          "x": 0.0,
          "n": 0
        },
        {
          "x": 2.0,
          "n": 0
        },
        {
          "x": 4.0,
          "n": 0
        },
        {
          "x": 6.0,
          "n": 0
        },
        {
          "x": 8.0,
          "n": 4
        },
        {
          "x": 10.0,
          "n": 7
        },
        {
          "x": 12.0,
          "n": 5
        },
        {
          "x": 14.0,
          "n": 3
        },
        {
          "x": 16.0,
          "n": 2
        },
        {
          "x": 18.0,
          "n": 2
        },
        {
          "x": 20.0,
          "n": 1
        },
        {
          "x": 22.0,
          "n": 1
        },
        {
          "x": 24.0,
          "n": 0
        },
        {
          "x": 26.0,
          "n": 0
        },
        {
          "x": 28.0,
          "n": 0
        },
        {
          "x": 30.0,
          "n": 0
        },
        {
          "x": 32.0,
          "n": 0
        },
        {
          "x": 34.0,
          "n": 0
        },
        {
          "x": 36.0,
          "n": 0
        },
        {
          "x": 38.0,
          "n": 0
        },
        {
          "x": 40.0,
          "n": 0
        },
        {
          "x": 42.0,
          "n": 0
        },
        {
          "x": 44.0,
          "n": 0
        },
        {
          "x": 46.0,
          "n": 0
        },
        {
          "x": 48.0,
          "n": 0
        }
      ],
      "defectMax": 22.54,
      "defectsPassing": 25
    },
    "dynamic": {
      "unit": "sigma",
      "limit": 4.5,
      "lo": -6.0,
      "hi": 24.0,
      "healthy": [
        {
          "x": -6.0,
          "n": 0
        },
        {
          "x": -5.0,
          "n": 0
        },
        {
          "x": -4.0,
          "n": 0
        },
        {
          "x": -3.0,
          "n": 1
        },
        {
          "x": -2.0,
          "n": 41
        },
        {
          "x": -1.0,
          "n": 126
        },
        {
          "x": 0.0,
          "n": 93
        },
        {
          "x": 1.0,
          "n": 31
        },
        {
          "x": 2.0,
          "n": 11
        },
        {
          "x": 3.0,
          "n": 9
        },
        {
          "x": 4.0,
          "n": 1
        },
        {
          "x": 5.0,
          "n": 1
        },
        {
          "x": 6.0,
          "n": 1
        },
        {
          "x": 7.0,
          "n": 0
        },
        {
          "x": 8.0,
          "n": 0
        },
        {
          "x": 9.0,
          "n": 0
        },
        {
          "x": 10.0,
          "n": 0
        },
        {
          "x": 11.0,
          "n": 0
        },
        {
          "x": 12.0,
          "n": 0
        },
        {
          "x": 13.0,
          "n": 0
        },
        {
          "x": 14.0,
          "n": 0
        },
        {
          "x": 15.0,
          "n": 0
        },
        {
          "x": 16.0,
          "n": 0
        },
        {
          "x": 17.0,
          "n": 0
        },
        {
          "x": 18.0,
          "n": 0
        },
        {
          "x": 19.0,
          "n": 0
        },
        {
          "x": 20.0,
          "n": 0
        },
        {
          "x": 21.0,
          "n": 0
        },
        {
          "x": 22.0,
          "n": 0
        },
        {
          "x": 23.0,
          "n": 0
        }
      ],
      "defect": [
        {
          "x": -6.0,
          "n": 0
        },
        {
          "x": -5.0,
          "n": 0
        },
        {
          "x": -4.0,
          "n": 0
        },
        {
          "x": -3.0,
          "n": 0
        },
        {
          "x": -2.0,
          "n": 3
        },
        {
          "x": -1.0,
          "n": 4
        },
        {
          "x": 0.0,
          "n": 5
        },
        {
          "x": 1.0,
          "n": 3
        },
        {
          "x": 2.0,
          "n": 1
        },
        {
          "x": 3.0,
          "n": 0
        },
        {
          "x": 4.0,
          "n": 0
        },
        {
          "x": 5.0,
          "n": 2
        },
        {
          "x": 6.0,
          "n": 0
        },
        {
          "x": 7.0,
          "n": 1
        },
        {
          "x": 8.0,
          "n": 0
        },
        {
          "x": 9.0,
          "n": 1
        },
        {
          "x": 10.0,
          "n": 0
        },
        {
          "x": 11.0,
          "n": 1
        },
        {
          "x": 12.0,
          "n": 0
        },
        {
          "x": 13.0,
          "n": 2
        },
        {
          "x": 14.0,
          "n": 0
        },
        {
          "x": 15.0,
          "n": 1
        },
        {
          "x": 16.0,
          "n": 0
        },
        {
          "x": 17.0,
          "n": 0
        },
        {
          "x": 18.0,
          "n": 0
        },
        {
          "x": 19.0,
          "n": 1
        },
        {
          "x": 20.0,
          "n": 0
        },
        {
          "x": 21.0,
          "n": 0
        },
        {
          "x": 22.0,
          "n": 0
        },
        {
          "x": 23.0,
          "n": 0
        }
      ],
      "defectsFlagged": 9,
      "healthyFlagged": 12
    }
  },
  "drift": {
    "hours": [
      0,
      24,
      96,
      168
    ],
    "p50": [
      10.246,
      10.38,
      10.582,
      10.749
    ],
    "p05": [
      7.731,
      7.888,
      8.016,
      7.997
    ],
    "p95": [
      13.123,
      13.653,
      14.402,
      14.679
    ],
    "subject": {
      "serial": "L01-0079",
      "values": [
        10.01,
        11.16,
        16.73,
        22.54
      ],
      "staticFail168h": 0
    },
    "datasheetHi": 50.0
  },
  "lotMap": {
    "lots": [
      {
        "lot": "L01",
        "n": 350,
        "defects": 25
      },
      {
        "lot": "L02",
        "n": 350,
        "defects": 14
      },
      {
        "lot": "L03",
        "n": 350,
        "defects": 19
      },
      {
        "lot": "L04",
        "n": 350,
        "defects": 65
      },
      {
        "lot": "L05",
        "n": 350,
        "defects": 24
      },
      {
        "lot": "L06",
        "n": 350,
        "defects": 27
      }
    ]
  },
  "reasons": {
    "subject": {
      "serial": "L06-0121",
      "lot": "L06",
      "staticFail168h": 0,
      "trace": {
        "Iddq_uA": [
          11.89,
          14.14,
          18.65,
          22.41
        ],
        "Ileak_nA": [
          21.88,
          22.04,
          21.88,
          21.9
        ],
        "Tpd_ns": [
          3.58,
          3.52,
          3.57,
          3.54
        ],
        "Vol_mV": [
          236.04,
          237.54,
          243.5,
          243.92
        ]
      },
      "codes": [
        {
          "code": "R-201",
          "severity": "high",
          "message": "Iddq_uA rose 19.0% in the first 24 hours; 95% of this lot rose under 11.8%."
        },
        {
          "code": "R-301",
          "severity": "high",
          "message": "Forecast 168h Iddq_uA implies a drift rate 1.1x the safety slope, predicted from the 0h and 24h reads alone. Recommend removal at hour 24."
        },
        {
          "code": "R-401",
          "severity": "medium",
          "message": "No single parameter trips its own limit, but the combined drift evidence across parameters is 201.0 against a 18.5 threshold (Iddq_uA 14.1 sigma, Vol_mV 1.1 sigma). Individually ordinary, jointly rare for this lot."
        }
      ]
    },
    "register": [
      {
        "code": "R-101",
        "title": "Abnormal level for this lot",
        "gate": "robust z of the 168h level > 6",
        "severity": "high",
        "fired": 155,
        "example": "Iddq_uA at 168h is 9.3 robust sigma above the lot median (53.07 uA vs lot median 10.8 uA). This also EXCEEDS the datasheet limit of 50 uA - a hard reject on static limits alone.",
        "exampleSerial": "L01-0002"
      },
      {
        "code": "R-201",
        "title": "Fast early movement",
        "gate": "robust z of the 0-24h delta > 5",
        "severity": "high",
        "fired": 85,
        "example": "Iddq_uA rose 25.6% in the first 24 hours; 95% of this lot rose under 10.6%.",
        "exampleSerial": "L01-0002"
      },
      {
        "code": "R-301",
        "title": "Forecast breaches the safety slope",
        "gate": "predicted slope > 1x the safety slope",
        "severity": "high",
        "fired": 104,
        "example": "Forecast 168h Iddq_uA implies a drift rate 1.5x the safety slope, predicted from the 0h and 24h reads alone. Recommend removal at hour 24.",
        "exampleSerial": "L01-0002"
      },
      {
        "code": "R-401",
        "title": "Pooled multivariate evidence",
        "gate": "pooled drift evidence > 18.47  (chi2 0.999, 4 dof)",
        "severity": "medium",
        "fired": 251,
        "example": "No single parameter trips its own limit, but the combined drift evidence across parameters is 4737.7 against a 18.5 threshold (Ileak_nA 43.5 sigma, Iddq_uA 41.0 sigma). Individually ordinary, jointly rare for this lot.",
        "exampleSerial": "L01-0002"
      },
      {
        "code": "R-501",
        "title": "Degradation accelerating",
        "gate": "curvature ratio > 2, accelerating not settling",
        "severity": "medium",
        "fired": 87,
        "example": "Vol_mV degradation is accelerating rather than settling: the late window is drifting 3.8x as fast as the early one (a part that is settling scores under 1.0).",
        "exampleSerial": "L01-0002"
      },
      {
        "code": "R-601",
        "title": "Lot exceeds PDA",
        "gate": "lot REJECT fraction > 5% (PDA gate)",
        "severity": "high",
        "fired": 3,
        "example": "Lot L01 has 5.4% rejected parts (19/350), exceeding the 5% PDA threshold - recommend lot-level review.",
        "exampleSerial": "L01"
      }
    ],
    "totalCodes": 682
  },
  "decide": {
    "bands": {
      "REJECT": {
        "parts": 105,
        "share": 0.05,
        "recall": 0.201,
        "overkill": 0.0038
      },
      "REJECT+WATCH": {
        "parts": 315,
        "share": 0.15,
        "recall": 0.81,
        "overkill": 0.0596
      }
    },
    "weights": [
      {
        "name": "static_margin",
        "weight": 0.3
      },
      {
        "name": "dynamic_outlier",
        "weight": 0.25
      },
      {
        "name": "predicted_drift",
        "weight": 0.2
      },
      {
        "name": "multivariate",
        "weight": 0.15
      },
      {
        "name": "curvature",
        "weight": 0.1
      }
    ],
    "pdaLimit": 0.05,
    "bandEdges": {
      "watch": 36.3,
      "reject": 61.2
    },
    "lots": [
      {
        "lot": "L01",
        "parts": 350,
        "reject": 19,
        "watch": 30,
        "rejectFrac": 0.0543,
        "breach": true
      },
      {
        "lot": "L02",
        "parts": 350,
        "reject": 12,
        "watch": 37,
        "rejectFrac": 0.0343,
        "breach": false
      },
      {
        "lot": "L03",
        "parts": 350,
        "reject": 8,
        "watch": 36,
        "rejectFrac": 0.0229,
        "breach": false
      },
      {
        "lot": "L04",
        "parts": 350,
        "reject": 34,
        "watch": 41,
        "rejectFrac": 0.0971,
        "breach": true
      },
      {
        "lot": "L05",
        "parts": 350,
        "reject": 12,
        "watch": 35,
        "rejectFrac": 0.0343,
        "breach": false
      },
      {
        "lot": "L06",
        "parts": 350,
        "reject": 20,
        "watch": 31,
        "rejectFrac": 0.0571,
        "breach": true
      }
    ],
    "scoreHist": [
      {
        "x": 0.0,
        "n": 0
      },
      {
        "x": 2.5,
        "n": 1
      },
      {
        "x": 5.0,
        "n": 41
      },
      {
        "x": 7.5,
        "n": 264
      },
      {
        "x": 10.0,
        "n": 425
      },
      {
        "x": 12.5,
        "n": 336
      },
      {
        "x": 15.0,
        "n": 210
      },
      {
        "x": 17.5,
        "n": 146
      },
      {
        "x": 20.0,
        "n": 105
      },
      {
        "x": 22.5,
        "n": 73
      },
      {
        "x": 25.0,
        "n": 58
      },
      {
        "x": 27.5,
        "n": 44
      },
      {
        "x": 30.0,
        "n": 31
      },
      {
        "x": 32.5,
        "n": 31
      },
      {
        "x": 35.0,
        "n": 35
      },
      {
        "x": 37.5,
        "n": 23
      },
      {
        "x": 40.0,
        "n": 23
      },
      {
        "x": 42.5,
        "n": 16
      },
      {
        "x": 45.0,
        "n": 28
      },
      {
        "x": 47.5,
        "n": 24
      },
      {
        "x": 50.0,
        "n": 23
      },
      {
        "x": 52.5,
        "n": 22
      },
      {
        "x": 55.0,
        "n": 17
      },
      {
        "x": 57.5,
        "n": 12
      },
      {
        "x": 60.0,
        "n": 13
      },
      {
        "x": 62.5,
        "n": 14
      },
      {
        "x": 65.0,
        "n": 6
      },
      {
        "x": 67.5,
        "n": 9
      },
      {
        "x": 70.0,
        "n": 4
      },
      {
        "x": 72.5,
        "n": 2
      },
      {
        "x": 75.0,
        "n": 0
      },
      {
        "x": 77.5,
        "n": 2
      },
      {
        "x": 80.0,
        "n": 2
      },
      {
        "x": 82.5,
        "n": 2
      },
      {
        "x": 85.0,
        "n": 5
      },
      {
        "x": 87.5,
        "n": 3
      },
      {
        "x": 90.0,
        "n": 8
      },
      {
        "x": 92.5,
        "n": 16
      },
      {
        "x": 95.0,
        "n": 6
      },
      {
        "x": 97.5,
        "n": 20
      }
    ]
  }
} as const;
