import Link from "next/link";
import { LAB } from "@/lib/lab-data";
import { FS, Frame, LimitLine, Tick, scale } from "@/components/charts/plot";
import { Trajectory } from "@/components/charts/charts";
import { Card, Meter, ReasonCode, Stamp, Steps, pct, unit } from "@/components/ui/kit";
import { C } from "@/lib/theme";

/* Landing sections. Every figure comes from LAB, generated by
 * web/scripts/export_lab_data.py from one call to src/pipeline.py::screen().
 * There is no hand-typed metric here - regenerate the dataset and the copy
 * follows it. */

const H = LAB.hero;
const U = unit(H.unit);
const K = LAB.compare;
const flagged = LAB.decide.bands["REJECT+WATCH"];

function Section({
  id, title, lede, children, tone,
}: { id?: string; title: string; lede?: React.ReactNode; children: React.ReactNode; tone?: "sheet" }) {
  return (
    <section id={id} className={tone === "sheet" ? "border-y border-rule bg-sheet" : undefined}>
      <div className="mx-auto max-w-[1200px] scroll-mt-4 px-4 py-16 sm:px-8 sm:py-20">
        <h2 className="wide max-w-[22ch] text-2xl font-extrabold tracking-[-0.01em] sm:text-3xl">{title}</h2>
        {lede && <p className="mt-4 max-w-prose text-lg text-graphite">{lede}</p>}
        <div className="mt-10">{children}</div>
      </div>
    </section>
  );
}

/* =====================================================================
 * THE GAP
 * ===================================================================== */
export function GapSection() {
  const staticRecall = 1 - LAB.headline.latentPassingDatasheet;
  return (
    <Section
      id="gap"
      title="The datasheet can only say pass."
      lede={<>{H.serial} started burn-in at {(H.trace as readonly number[])[0]} {U} and finished at {H.value168} {U}. It more than doubled while its lot barely moved. It passed, because {H.value168} is less than {H.usl}.</>}
    >
      <div className="grid gap-4 md:grid-cols-2">
        <Card className="p-6">
          <h3 className="text-sm font-semibold text-graphite">Traditional screening asks</h3>
          <p className="mt-1 text-lg font-semibold">Is it under the datasheet limit?</p>
          <p className="mt-4 text-3xl font-bold">{H.value168} &lt; {H.usl} {U}</p>
          <div className="mt-5 flex items-center gap-3">
            <Stamp v="PASS" size="lg" />
            <span className="text-sm text-graphite">The component ships.</span>
          </div>
        </Card>
        <Card className="p-6">
          <h3 className="text-sm font-semibold text-graphite">SENTINEL asks</h3>
          <p className="mt-1 text-lg font-semibold">Is it behaving like the rest of its lot?</p>
          <p className="mt-4 text-3xl font-bold text-reject">{H.driftZ}σ from its lot</p>
          <div className="mt-5 flex items-center gap-3">
            <Stamp v="REJECT" size="lg" />
            <span className="text-sm text-graphite">Risk {H.riskScore} of 100, with a reason attached.</span>
          </div>
        </Card>
      </div>

      <Card className="mt-4 p-6">
        <h3 className="text-base font-bold">
          Across all {LAB.headline.parts.toLocaleString()} components, {LAB.headline.latentDefects} are latent
          defects ({pct(LAB.headline.defectRate, 1)}). How many does each screen catch?
        </h3>
        <div className="mt-5 space-y-4">
          {[
            { k: "Datasheet limits at 168 h", v: staticRecall, c: C.reject, s: "Every latent defect passes every static limit." },
            { k: "SENTINEL, watch or reject", v: flagged.recall, c: C.cobalt, s: `At ${pct(flagged.overkill, 1)} of healthy parts flagged.` },
          ].map((r) => (
            <div key={r.k} className="grid items-center gap-x-6 gap-y-1 sm:grid-cols-[220px_minmax(0,1fr)_72px]">
              <div className="text-sm font-semibold">{r.k}</div>
              <Meter value={r.v} max={1} height={14} color={r.c} />
              <div className="wide text-xl font-black sm:text-right" style={{ color: r.c }}>{pct(r.v, 0)}</div>
              <p className="text-xs text-graphite sm:col-start-2">{r.s}</p>
            </div>
          ))}
        </div>
      </Card>
    </Section>
  );
}

/* =====================================================================
 * MODULE A - same lot, two references
 * ===================================================================== */
type Bin = { readonly x: number; readonly n: number };

function CompareHist({
  healthy, defect, lo, hi, limit, limitLabel, xLabel, ticks,
}: {
  healthy: readonly Bin[]; defect: readonly Bin[]; lo: number; hi: number;
  limit: number; limitLabel: string; xLabel: string; ticks: number[];
}) {
  const w = 560, h = 230;
  const pad: [number, number, number, number] = [24, 16, 42, 16];
  const [pt, pr, pb, pl] = pad;
  const x0 = pl, x1 = w - pr, y0 = pt, y1 = h - pb;
  const peak = Math.max(...healthy.map((b) => b.n), 1);
  const bw = (x1 - x0) / healthy.length;
  const yOf = (n: number) => y1 - Math.pow(n / peak, 0.62) * (y1 - y0);
  const xl = scale(limit, lo, hi, x0, x1);

  return (
    <Frame w={w} h={h} pad={pad} caption={xLabel}>
      <rect x={xl} y={y0} width={Math.max(0, x1 - xl)} height={y1 - y0} fill={C.reject} fillOpacity="0.06" />
      {healthy.map((b, i) => b.n ? (
        <rect key={`h${i}`} x={x0 + i * bw + 0.8} y={yOf(b.n)} width={bw - 1.6} height={y1 - yOf(b.n)} fill={C.cobalt} fillOpacity="0.3" />
      ) : null)}
      {defect.map((b, i) => b.n ? (
        <rect key={`d${i}`} x={x0 + i * bw + 0.8} y={yOf(b.n)} width={bw - 1.6} height={y1 - yOf(b.n)} fill={C.reject} fillOpacity="0.9" />
      ) : null)}
      <LimitLine x={xl} top={y0 - 12} bottom={y1} label={limitLabel} side={xl > x1 - 120 ? "left" : "right"} />
      {ticks.map((t) => <Tick key={t} x={scale(t, lo, hi, x0, x1)} y={y1 + 16} label={String(t)} />)}
      <text x={(x0 + x1) / 2} y={h - 4} textAnchor="middle" fontSize={FS} fill={C.mute}>{xLabel}</text>
    </Frame>
  );
}

export function DetectionSection() {
  return (
    <Section
      id="detection"
      tone="sheet"
      title="Module A judges each part against its own lot."
      lede={<>Lots differ from each other, so a fixed limit has to be loose enough for all of them. A lot-relative reference is as tight as the lot in front of you. Same lot, same {K.nDefect} latent defects, two references:</>}
    >
      <div className="grid gap-4 lg:grid-cols-2">
        <Card className="p-5">
          <h3 className="text-base font-bold">Against the datasheet</h3>
          <p className="mt-1 text-sm text-graphite">
            Lot {K.lot}, {K.param} at 168 h. The limit flags{" "}
            <strong className="text-reject">{K.nDefect - K.static.defectsPassing} of {K.nDefect}</strong> latent defects.
          </p>
          <div className="mt-4">
            <CompareHist healthy={K.static.healthy} defect={K.static.defect} lo={K.static.lo} hi={K.static.hi}
              limit={K.static.limit} limitLabel={`Limit ${K.static.limit} ${unit(K.static.unit)}`}
              xLabel={`${K.param} at 168 h, ${unit(K.static.unit)}`} ticks={[0, 10, 20, 30, 40, 50]} />
          </div>
        </Card>
        <Card className="p-5">
          <h3 className="text-base font-bold">Against the lot</h3>
          <p className="mt-1 text-sm text-graphite">
            The same parts as robust deviation from lot {K.lot} (L2). At {K.dynamic.limit}σ it flags{" "}
            <strong className="text-cobalt">{K.dynamic.defectsFlagged} of {K.nDefect}</strong>, at the cost of{" "}
            {K.dynamic.healthyFlagged} healthy parts.
          </p>
          <div className="mt-4">
            <CompareHist healthy={K.dynamic.healthy} defect={K.dynamic.defect} lo={K.dynamic.lo} hi={K.dynamic.hi}
              limit={K.dynamic.limit} limitLabel={`${K.dynamic.limit}σ`}
              xLabel="Robust deviation from the lot, σ" ticks={[-5, 0, 5, 10, 15, 20]} />
          </div>
        </Card>
      </div>

      <div className="mt-4 grid gap-4 md:grid-cols-3">
        {[
          { t: "L1 datasheet limit", d: `Kept in the pipeline permanently, so the gap stays visible. It catches ${pct(1 - LAB.headline.latentPassingDatasheet, 0)} of latent defects here.` },
          { t: "L2 dynamic part average", d: "The worst robust z across every parameter, computed inside the lot. Median and 1.4826·MAD, never mean and σ: a mean-based limit is inflated by the outlier it hunts." },
          { t: "L3 pooled evidence", d: "A one-sided sum of squared robust z over four drift axes, against a χ² threshold. It catches parts that are only moderately high on several axes at once." },
        ].map((l) => (
          <Card key={l.t} className="p-5">
            <h3 className="text-sm font-bold">{l.t}</h3>
            <p className="mt-2 text-sm text-graphite">{l.d}</p>
          </Card>
        ))}
      </div>
      <p className="mt-4 max-w-prose text-sm text-graphite">
        L2 alone is limited by measurement noise, not by the model. Pooling the layers with the
        forecast into one fused score is what reaches {pct(flagged.recall, 0)} across the whole dataset.
      </p>
    </Section>
  );
}

/* =====================================================================
 * MODULE B
 * ===================================================================== */
export function ForecastSection() {
  const trace = H.trace as readonly number[];
  return (
    <Section
      id="forecast"
      title="Module B looks ahead from hour 24."
      lede="It forecasts each part's 168 hour value from its first two reads, so the parts most likely to fail can leave the oven early."
    >
      <div className="grid gap-4 xl:grid-cols-[minmax(0,7fr)_minmax(0,5fr)]">
        <Card className="p-5">
          <h3 className="text-base font-bold">{H.serial}, forecast against what happened</h3>
          <div className="mt-4">
            <Trajectory
              hours={[...H.hours]} values={[...trace]}
              envelope={{ p05: [...H.p05], p50: [...H.p50], p95: [...H.p95] }}
              usl={H.usl} forecast={H.forecast168} unitName={H.unit}
            />
          </div>
          <p className="mt-3 text-sm text-graphite">
            The honest case. From its first 24 hours the forecast put this part at {H.forecast168} {U};
            it reached {trace[3]} {U}. Its drift sped up after hour 24, which two reads cannot see. Module A
            catches it; Module B does not.
          </p>
        </Card>

        <div className="space-y-4">
          <Card className="p-5">
            <h3 className="text-sm font-bold">The decision at hour 24</h3>
            <Steps
              className="mt-4"
              steps={[
                { k: "Forecast", v: "The 168 h value from the 0 h and 24 h reads" },
                { k: "Bound", v: "Take the optimistic 0.90 quantile" },
                { k: "Compare", v: "Forecast slope against the safety slope" },
                { k: "Act", v: "Pull the part early, or continue the soak" },
              ]}
            />
          </Card>
          <Card className="p-5">
            <h3 className="text-sm font-bold">What it does and does not claim</h3>
            <p className="mt-2 text-sm text-graphite">
              Module B is a triage layer, not a replacement for the full 168 hour screen. It adds
              little to detection. What it buys is time: <strong className="text-ink">144 oven-hours</strong>{" "}
              for every part pulled at hour 24, on the resource that limits the whole screening line.
            </p>
          </Card>
        </div>
      </div>
    </Section>
  );
}

/* =====================================================================
 * EXPLAINABILITY
 * ===================================================================== */
export function ReasonsSection() {
  const R = LAB.reasons;
  const codes = R.subject.codes as readonly { code: string; severity: string; message: string }[];
  const register = R.register as readonly { code: string; title: string; gate: string; severity: string; fired: number }[];
  const peak = Math.max(...register.map((x) => x.fired));

  return (
    <Section
      id="reasons"
      tone="sheet"
      title="Every flag carries a reason an inspector can check."
      lede={<>Not &ldquo;the model considers this part risky&rdquo;, but a sentence with the measured value, the lot&rsquo;s reference and the threshold, which an engineer can verify and, if they disagree, overrule.</>}
    >
      <div className="grid gap-4 xl:grid-cols-[minmax(0,7fr)_minmax(0,5fr)]">
        <Card className="p-5">
          <div className="flex flex-wrap items-center justify-between gap-3 border-b border-hair pb-3">
            <div>
              <h3 className="wide text-lg font-extrabold">{R.subject.serial}</h3>
              <p className="text-sm text-graphite">Lot {R.subject.lot}. Passes every datasheet limit at 168 h.</p>
            </div>
            <Link href={`/console/reports?id=${R.subject.serial}`} className="btn-quiet">Open its report</Link>
          </div>
          <ul className="divide-y divide-hair">
            {codes.map((c) => (
              <ReasonCode key={c.code} r={{ ...c, title: register.find((r) => r.code === c.code)?.title }} />
            ))}
          </ul>
        </Card>

        <Card className="p-5">
          <h3 className="text-sm font-bold">The reason codes</h3>
          <p className="text-sm text-graphite">
            Rules, not model output. {R.totalCodes.toLocaleString()} fired in this run.
          </p>
          <ul className="mt-3 divide-y divide-hair">
            {register.map((r) => (
              <li key={r.code} className="py-2.5">
                <div className="flex items-baseline gap-3 text-sm">
                  <span className="font-bold">{r.code}</span>
                  <span className="min-w-0 flex-1">{r.title}</span>
                  <span className="text-graphite">{r.fired.toLocaleString()}</span>
                </div>
                <div className="mt-1.5">
                  <Meter value={r.fired} max={peak} height={4} color={r.severity === "high" ? C.reject : C.watch} />
                </div>
              </li>
            ))}
          </ul>
          <p className="mt-3 text-xs text-graphite">
            Attribution is exact. For the robust-z layers, a part&rsquo;s contribution to the score
            is its z-score; there is no surrogate model between the decision and its explanation.
          </p>
        </Card>
      </div>
    </Section>
  );
}

/* ------------------------------------------------------------ closing */
export function ConsoleCta() {
  const screens = [
    ["Overview", "disposition, lot health, the investigation queue"],
    ["Screen a data log", "upload a CSV and run live inference"],
    ["Lots", "distribution, wafer map, PDA gate"],
    ["Components", "every part, with its full record"],
    ["Method and policy", "the modules, and the cost of a missed defect"],
    ["Reports", "the signed record for a traveller"],
  ];
  return (
    <section className="mx-auto max-w-[1200px] px-4 py-16 sm:px-8 sm:py-20">
      <div className="grid gap-8 lg:grid-cols-[minmax(0,5fr)_minmax(0,7fr)] lg:items-start">
        <div>
          <h2 className="wide text-2xl font-extrabold sm:text-3xl">Now look at all {LAB.headline.parts.toLocaleString()}.</h2>
          <p className="mt-3 max-w-prose text-lg text-graphite">
            The console holds every screened component, its evidence and its forecast, and a
            printable record for each one.
          </p>
          <Link href="/console" className="btn-primary mt-6 px-5 py-2.5 text-base">Open the console</Link>
        </div>
        <dl className="card grid divide-y divide-hair sm:grid-cols-2 sm:divide-y-0">
          {screens.map(([k, v], i) => (
            <div key={k} className={`px-5 py-4 ${i >= 2 ? "sm:border-t sm:border-hair" : ""} ${i % 2 ? "sm:border-l sm:border-hair" : ""}`}>
              <dt className="font-semibold">{k}</dt>
              <dd className="text-sm text-graphite">{v}</dd>
            </div>
          ))}
        </dl>
      </div>
    </section>
  );
}
