"use client";

import Link from "next/link";
import { LAB } from "@/lib/lab-data";
import {
  ChartNote, FlowTape, Meter, Panel, PanelHead, SectionHead, SeverityTag,
  VerdictChip, num, pct, unit,
} from "@/components/ui/kit";
import { cn } from "@/lib/utils";

const H = LAB.hero;
const U = unit(H.unit);

/* Landing sections. Every figure comes from LAB, which is generated by
 * web/scripts/export_lab_data.py from one call to src/pipeline.py::screen().
 * There is no hand-typed metric on this page - regenerate the dataset and the
 * copy follows it. */

function Wrap({
  id, children, tone = "card",
}: { id?: string; children: React.ReactNode; tone?: "card" | "panel" }) {
  return (
    <section
      id={id}
      className={cn(
        "border-b border-lab-rule",
        tone === "panel" ? "bg-lab-panel" : "bg-lab-card"
      )}
    >
      <div className="mx-auto max-w-[1400px] px-4 py-12 sm:px-6">{children}</div>
    </section>
  );
}

/* =====================================================================
 * §4  THE LIMITS CAN MISS THE RISK
 * ===================================================================== */

/** The one visual the whole project rests on: a limit, a part just under it,
 *  and the lot the part is supposed to resemble sitting far below. */
function LimitVsLot() {
  const w = 620, h = 340;
  const pl = 76, pr = 26, pt = 26, pb = 34;
  const x0 = pl, x1 = w - pr, y0 = pt, y1 = h - pb;
  const lo = 0, hi = 55;
  const Y = (v: number) => y1 - ((v - lo) / (hi - lo)) * (y1 - y0);

  const bins = LAB.hero.lotHist as readonly { x: number; n: number }[];
  const defects = LAB.hero.lotDefectHist as readonly { x: number; n: number }[];
  const peak = Math.max(...bins.map((b) => b.n), 1);
  const bh = (y1 - y0) / bins.length;
  // density grows to the right from the axis; sqrt compression so the
  // lognormal tail stays visible against one very tall central bin
  const wOf = (n: number) => Math.pow(n / peak, 0.62) * (x1 - x0) * 0.52;

  const yUsl = Y(H.usl);
  const yPart = Y(H.value168);
  const yMed = Y(H.lotMedian168);

  return (
    <svg viewBox={`0 0 ${w} ${h}`} className="w-full" role="img"
      aria-label="Datasheet limit against the lot population">
      <title>The component sits under the datasheet limit but far outside its lot</title>
      <defs>
        <pattern id="gp-lv" width="10" height="10" patternUnits="userSpaceOnUse">
          <path d="M10 0H0V10" fill="none" stroke="#0F1317" strokeOpacity="0.05" strokeWidth="1" />
        </pattern>
        <marker id="arw" markerWidth="7" markerHeight="7" refX="3.5" refY="3.5" orient="auto">
          <path d="M0,0 L7,3.5 L0,7 Z" fill="#A81E12" />
        </marker>
      </defs>

      <rect x={x0} y={y0} width={x1 - x0} height={y1 - y0} fill="#FCFCFB" />
      <rect x={x0} y={y0} width={x1 - x0} height={y1 - y0} fill="url(#gp-lv)" />

      {/* the lot's own dynamic band: median +/- 3 and 6 robust sigma */}
      {[3, 6].map((k) => {
        const top = Y(H.lotMedian168 + k * H.lotSigma168);
        return (
          <g key={k}>
            <line x1={x0} x2={x1} y1={top} y2={top} stroke="#12508C"
              strokeOpacity="0.45" strokeWidth="1" strokeDasharray="2 3" />
            <text x={x1 - 3} y={top - 3} textAnchor="end" className="font-mono"
              style={{ fontSize: 8, fill: "#12508C", fillOpacity: 0.8 }}>
              lot +{k}σ
            </text>
          </g>
        );
      })}

      {/* lot population, drawn as a density from the axis */}
      {bins.map((b, i) =>
        b.n ? (
          <rect key={`p${i}`} x={x0} y={y1 - (i + 1) * bh + 0.4}
            width={wOf(b.n)} height={Math.max(0.8, bh - 0.8)}
            fill="#12508C" fillOpacity="0.3" />
        ) : null
      )}
      {defects.map((b, i) =>
        b.n ? (
          <rect key={`d${i}`} x={x0} y={y1 - (i + 1) * bh + 0.4}
            width={wOf(b.n)} height={Math.max(0.8, bh - 0.8)}
            fill="#A81E12" fillOpacity="0.75" />
        ) : null
      )}

      {/* lot median */}
      <line x1={x0} x2={x1} y1={yMed} y2={yMed} stroke="#0F1317" strokeWidth="1.25" />
      <text x={x0 + 6} y={yMed - 5} className="font-mono"
        style={{ fontSize: 9, fill: "#0F1317", fontWeight: 700 }}>
        LOT MEDIAN {H.lotMedian168} {U}
      </text>

      {/* datasheet limit */}
      <line x1={x0} x2={x1} y1={yUsl} y2={yUsl} stroke="#A81E12" strokeWidth="2" />
      <text x={x0 + 6} y={yUsl - 6} className="font-mono"
        style={{ fontSize: 10, fill: "#A81E12", fontWeight: 700, letterSpacing: "0.06em" }}>
        DATASHEET LIMIT {H.usl} {U}
      </text>

      {/* the component */}
      <circle cx={x0 + (x1 - x0) * 0.62} cy={yPart} r="6.5" fill="#A81E12" />
      <circle cx={x0 + (x1 - x0) * 0.62} cy={yPart} r="11" fill="none"
        stroke="#A81E12" strokeWidth="1.1" strokeOpacity="0.45" />
      <text x={x0 + (x1 - x0) * 0.62 + 16} y={yPart + 4} className="font-mono"
        style={{ fontSize: 11, fill: "#A81E12", fontWeight: 700 }}>
        {H.value168} {U}
      </text>
      <text x={x0 + (x1 - x0) * 0.62 + 16} y={yPart + 16} className="font-mono"
        style={{ fontSize: 8, fill: "#59616D" }}>
        {H.serial} · passes by {H.marginLeft} {U}
      </text>

      {/* the argument: an arrow from the part down to where its lot lives */}
      <line
        x1={x0 + (x1 - x0) * 0.62} x2={x0 + (x1 - x0) * 0.62}
        y1={yPart + 13} y2={yMed - 8}
        stroke="#A81E12" strokeWidth="1.2" strokeDasharray="3 3" markerEnd="url(#arw)"
      />
      <text x={x0 + (x1 - x0) * 0.62 - 10} y={(yPart + yMed) / 2} textAnchor="end"
        className="font-mono" style={{ fontSize: 9, fill: "#A81E12", fontWeight: 700 }}>
        {H.driftZ}σ
      </text>
      <text x={x0 + (x1 - x0) * 0.62 - 10} y={(yPart + yMed) / 2 + 11} textAnchor="end"
        className="font-mono" style={{ fontSize: 8, fill: "#59616D" }}>
        abnormal vs its lot
      </text>

      {/* value axis */}
      {[0, 10, 20, 30, 40, 50].map((v) => (
        <g key={v}>
          <line x1={x0 - 4} x2={x0} y1={Y(v)} y2={Y(v)} stroke="#9CA2AB" />
          <text x={x0 - 7} y={Y(v) + 3} textAnchor="end" className="font-mono"
            style={{ fontSize: 8.5, fill: "#8C939E" }}>
            {v}
          </text>
        </g>
      ))}
      <text x={18} y={(y0 + y1) / 2} textAnchor="middle" className="font-mono"
        transform={`rotate(-90 18 ${(y0 + y1) / 2})`}
        style={{ fontSize: 8.5, fill: "#8C939E", letterSpacing: "0.12em" }}>
        {H.param} AT 168 h ({U})
      </text>
      <text x={(x0 + x1) / 2} y={h - 4} textAnchor="middle" className="font-mono"
        style={{ fontSize: 8, fill: "#8C939E", letterSpacing: "0.1em" }}>
        LOT {H.lot} POPULATION DENSITY · n={H.lotN} · RED = LABELLED LATENT DEFECTS
      </text>
      <rect x={x0} y={y0} width={x1 - x0} height={y1 - y0} fill="none" stroke="#9CA2AB" />
    </svg>
  );
}

export function ProblemSection() {
  return (
    <Wrap id="problem" tone="panel">
      <SectionHead
        index="01"
        title="The limits can miss the risk"
        note="a real component from the screened dataset"
      />

      <div className="grid gap-px bg-lab-rule xl:grid-cols-[minmax(0,1fr)_minmax(0,660px)]">
        {/* ------------------------------------------------ the verdicts */}
        <div className="bg-lab-card p-5">
          <div className="flex flex-wrap items-baseline gap-3">
            <span className="label">Component</span>
            <span className="readout text-[20px] font-bold text-lab-ink">{H.serial}</span>
            <span className="font-mono text-[10px] text-lab-faint">
              lot {H.lot} · wafer {H.wafer}
            </span>
          </div>

          <div className="mt-4 grid grid-cols-2 gap-px bg-lab-hair">
            {[
              { k: `${H.param} @ 168 h`, v: `${H.value168} ${U}`, tone: "text-lab-ink" },
              { k: "Datasheet limit", v: `${H.usl} ${U}`, tone: "text-lab-ink" },
              { k: "Margin remaining", v: `${H.marginLeft} ${U}`, tone: "text-sig-red" },
              { k: "Consumed", v: pct(H.uslFrac, 1) + " of limit", tone: "text-sig-red" },
            ].map((f) => (
              <div key={f.k} className="bg-lab-card px-3 py-2.5">
                <div className="label">{f.k}</div>
                <div className={cn("readout mt-1 text-[16px] font-semibold leading-none", f.tone)}>
                  {f.v}
                </div>
              </div>
            ))}
          </div>

          {/* the two verdicts, side by side */}
          <div className="mt-4 grid gap-px bg-lab-rule sm:grid-cols-2">
            <div className="bg-lab-card px-3.5 py-3.5">
              <div className="label">Traditional screening</div>
              <div className="readout mt-2 font-mono text-[11px] text-lab-dim">
                {H.value168} &lt; {H.usl} {U}
              </div>
              <div className="mt-2 inline-flex items-center gap-1.5 border border-sig-green/35 bg-sig-green/[0.08] px-2 py-1">
                <span className="inline-block h-[5px] w-[5px] rounded-full bg-sig-green" />
                <span className="font-mono text-[11px] font-bold uppercase tracking-label text-sig-green">
                  PASS
                </span>
              </div>
              <p className="mt-2.5 font-mono text-[9px] leading-relaxed text-lab-faint">
                The component ships. Nothing in the datasheet test is violated.
              </p>
            </div>

            <div className="bg-lab-card px-3.5 py-3.5">
              <div className="label">SENTINEL</div>
              <div className="readout mt-2 font-mono text-[11px] text-lab-dim">
                {H.driftZ}σ above the lot · pooled {H.l3}
              </div>
              <div className="mt-2">
                <VerdictChip v={H.verdict as "REJECT"} size="lg" />
              </div>
              <p className="mt-2.5 font-mono text-[9px] leading-relaxed text-lab-faint">
                Risk {H.riskScore}/100. Flagged on how far it moved relative to its own lot.
              </p>
            </div>
          </div>

          <div className="mt-4 space-y-2">
            {[
              { k: "Lot median at 168 h", v: `${H.lotMedian168} ${U}` },
              { k: "Lot robust σ at 168 h", v: `${H.lotSigma168} ${U}` },
              { k: "Lot-relative drift deviation", v: `${H.driftZ} robust σ`, tone: "text-sig-red" },
              { k: "Pooled multivariate evidence", v: `${H.l3} vs 18.5 threshold`, tone: "text-sig-red" },
              { k: "Screening risk score", v: `${H.riskScore} / 100`, tone: "text-sig-red" },
            ].map((r) => (
              <div key={r.k} className="flex items-baseline justify-between gap-3 border-b border-lab-hair pb-1.5">
                <span className="font-mono text-[10px] text-lab-dim">{r.k}</span>
                <span className={cn("readout text-[11px] font-semibold", r.tone ?? "text-lab-ink")}>
                  {r.v}
                </span>
              </div>
            ))}
          </div>

          <p className="mt-4 border-l-[3px] border-l-sig-red bg-lab-panel px-3 py-2.5 text-[12px] leading-relaxed text-lab-ink">
            This component started at {(H.trace as readonly number[])[0]} {U} and finished at{" "}
            {H.value168} {U} — it more than doubled while its lot barely moved. It passed because{" "}
            {H.value168} is less than {H.usl}. Under a lot-relative reference it is one of the
            most abnormal parts in {H.lotN} components.
          </p>
        </div>

        {/* -------------------------------------------------- the visual */}
        <div className="bg-lab-card p-5">
          <PanelHead
            title="One limit, two references"
            meta={`lot ${H.lot} · ${H.param} at 168 h`}
            className="-mx-5 -mt-5 mb-3 px-5"
          />
          <LimitVsLot />
          <ChartNote>
            The datasheet limit is a single horizontal line drawn for every component ever made
            to this part number. The lot is where these particular components actually live —{" "}
            {H.lotMedian168} {U} with a robust σ of {H.lotSigma168}. Judged against the line, this
            component is fine. Judged against its siblings, it is nowhere near them.
          </ChartNote>
        </div>
      </div>

      {/* the population-level consequence */}
      <div className="mt-px grid gap-px bg-lab-rule sm:grid-cols-3">
        {[
          {
            k: "Latent defects in the dataset",
            v: LAB.headline.latentDefects.toLocaleString(),
            s: `${pct(LAB.headline.defectRate, 1)} of ${LAB.headline.parts.toLocaleString()} components`,
          },
          {
            k: "…that pass every static limit at 168 h",
            v: pct(LAB.headline.latentPassingDatasheet, 0),
            s: "static screening catches none of them",
            tone: "text-sig-red",
          },
          {
            k: "…caught by SENTINEL",
            v: pct(LAB.decide.bands["REJECT+WATCH"].recall, 1),
            s: `at ${pct(LAB.decide.bands["REJECT+WATCH"].overkill, 1)} overkill on healthy parts`,
            tone: "text-sig-blue",
          },
        ].map((c) => (
          <div key={c.k} className="bg-lab-card px-4 py-4">
            <div className="label">{c.k}</div>
            <div className={cn("readout mt-1.5 text-[30px] font-bold leading-none", c.tone ?? "text-lab-ink")}>
              {c.v}
            </div>
            <div className="mt-1.5 font-mono text-[9px] text-lab-faint">{c.s}</div>
          </div>
        ))}
      </div>
    </Wrap>
  );
}

/* =====================================================================
 * §6  MODULE A
 * ===================================================================== */
export function ModuleASection() {
  return (
    <Wrap id="module-a">
      <SectionHead
        index="Module A"
        title="Dynamic lot-relative detection"
        note="is this component behaving like its siblings?"
      />

      <div className="grid gap-px bg-lab-rule lg:grid-cols-2">
        <div className="bg-lab-panel p-5">
          <div className="label mb-2.5">Traditional</div>
          <FlowTape
            steps={[
              { k: "Measure", v: `${H.param} = ${H.value168} ${U}` },
              { k: "Compare", v: `against ${H.usl} ${U} datasheet limit` },
              { k: "Decide", v: "PASS", tone: "text-sig-green" },
            ]}
          />
          <p className="mt-3 font-mono text-[9.5px] leading-relaxed text-lab-faint">
            One reading, one fixed number. The reference never changes and never knew anything
            about this production lot.
          </p>
        </div>

        <div className="bg-lab-card p-5">
          <div className="label mb-2.5">SENTINEL</div>
          <FlowTape
            steps={[
              { k: "Measure", v: `${H.param} trace, 0 → 168 h` },
              { k: "Lot distribution", v: `median ${H.lotMedian168} ${U} · robust σ ${H.lotSigma168}` },
              { k: "Robust deviation", v: `${H.driftZ}σ — median & 1.4826·MAD` },
              { k: "Multivariate evidence", v: `${H.l3} pooled across 4 drift axes` },
              { k: "Anomaly score", v: `risk ${H.riskScore}/100`, tone: "text-sig-red" },
            ]}
          />
        </div>
      </div>

      {/* the three layers */}
      <div className="mt-px grid gap-px bg-lab-rule md:grid-cols-3">
        {[
          {
            tag: "L1 — Static limit",
            v: H.staticVerdict,
            tone: H.staticVerdict === "PASS" ? "text-sig-green" : "text-sig-red",
            body: `Datasheet upper limit at any read point. Kept in the pipeline permanently, because the demo has to be able to show it catching ${pct(1 - LAB.headline.latentPassingDatasheet, 0)} of latent defects.`,
          },
          {
            tag: "L2 — Worst-case lot deviation",
            v: `${H.l2}σ`,
            tone: "text-sig-red",
            body: "Dynamic Part Average Testing, the AEC-Q001 method. Worst robust z across every parameter and view, computed inside the lot. Median and MAD, never mean and σ — a mean-based limit is inflated by the outlier it is hunting.",
          },
          {
            tag: "L3 — Pooled evidence",
            v: `${H.l3}`,
            tone: "text-sig-red",
            body: "One-sided sum of squared robust z over the four drift axes, against a χ²(0.999) threshold of 18.5. Catches components that are individually ordinary on every axis but jointly rare.",
          },
        ].map((l) => (
          <div key={l.tag} className="bg-lab-card px-4 py-4">
            <div className="flex items-baseline justify-between gap-2">
              <span className="font-mono text-[9.5px] font-bold uppercase tracking-label text-lab-ink">
                {l.tag}
              </span>
              <span className={cn("readout text-[17px] font-bold leading-none", l.tone)}>{l.v}</span>
            </div>
            <p className="mt-2.5 font-mono text-[9px] leading-relaxed text-lab-faint">{l.body}</p>
          </div>
        ))}
      </div>

      <div className="mt-px flex flex-wrap items-center gap-3 bg-lab-ink px-4 py-3">
        <span className="font-mono text-[9px] uppercase tracking-label text-lab-faint">Final</span>
        <span className="font-mono text-[13px] font-bold uppercase tracking-label text-lab-panel">
          Flagged — {H.serial}
        </span>
        <span className="font-mono text-[10px] text-lab-faint">
          inside every datasheet limit, outside its own lot
        </span>
        <Link
          href="/console/analysis"
          className="ml-auto border border-lab-panel/30 px-3 py-1.5 font-mono text-[10px] uppercase tracking-label text-lab-panel hover:bg-lab-panel/10"
        >
          Open the method →
        </Link>
      </div>
    </Wrap>
  );
}

/* =====================================================================
 * §7  MODULE B
 * ===================================================================== */
function ForecastDiagram() {
  const w = 620, h = 190;
  const pl = 46, pr = 60, pt = 34, pb = 34;
  const x0 = pl, x1 = w - pr, y0 = pt, y1 = h - pb;
  const vs = H.trace as readonly number[];
  const hs = H.hours as readonly number[];
  const hi = Math.max(H.usl * 1.04, ...vs, H.forecast168);
  const X = (t: number) => x0 + (t / 168) * (x1 - x0);
  const Y = (v: number) => y1 - (v / hi) * (y1 - y0);

  return (
    <svg viewBox={`0 0 ${w} ${h}`} className="w-full" role="img"
      aria-label="Observed window and forecast window">
      <title>Module B forecasts the 168 h value from the first 24 hours</title>
      <defs>
        <pattern id="gp-fd" width="10" height="10" patternUnits="userSpaceOnUse">
          <path d="M10 0H0V10" fill="none" stroke="#0F1317" strokeOpacity="0.05" strokeWidth="1" />
        </pattern>
      </defs>

      {/* observed vs forecast regions */}
      <rect x={x0} y={y0} width={X(24) - x0} height={y1 - y0} fill="#12508C" fillOpacity="0.07" />
      <rect x={X(24)} y={y0} width={x1 - X(24)} height={y1 - y0} fill="#9A5B06" fillOpacity="0.05" />
      <rect x={x0} y={y0} width={x1 - x0} height={y1 - y0} fill="url(#gp-fd)" />

      <text x={(x0 + X(24)) / 2} y={y0 - 10} textAnchor="middle" className="font-mono"
        style={{ fontSize: 9, fill: "#12508C", fontWeight: 700, letterSpacing: "0.12em" }}>
        OBSERVED
      </text>
      <text x={(X(24) + x1) / 2} y={y0 - 10} textAnchor="middle" className="font-mono"
        style={{ fontSize: 9, fill: "#9A5B06", fontWeight: 700, letterSpacing: "0.12em" }}>
        FORECAST
      </text>
      <line x1={X(24)} x2={X(24)} y1={y0 - 4} y2={y1} stroke="#0F1317" strokeWidth="1.25" />

      {/* datasheet limit */}
      <line x1={x0} x2={x1} y1={Y(H.usl)} y2={Y(H.usl)} stroke="#A81E12" strokeWidth="1.2" />
      <text x={x1 + 4} y={Y(H.usl) + 3} className="font-mono"
        style={{ fontSize: 7.5, fill: "#A81E12", fontWeight: 700 }}>
        USL {H.usl}
      </text>

      {/* measured 0->24 solid */}
      <path d={`M${X(0)},${Y(vs[0])} L${X(24)},${Y(vs[1])}`} fill="none"
        stroke="#A81E12" strokeWidth="2.1" />
      {/* forecast 24->168 dashed */}
      <path d={`M${X(24)},${Y(vs[1])} L${X(168)},${Y(H.forecast168)}`} fill="none"
        stroke="#9A5B06" strokeWidth="1.9" strokeDasharray="6 4" />
      {/* what actually happened, faint, for verification */}
      <path d={`M${X(24)},${Y(vs[1])} L${X(96)},${Y(vs[2])} L${X(168)},${Y(vs[3])}`}
        fill="none" stroke="#A81E12" strokeWidth="1.2" strokeOpacity="0.3" strokeDasharray="2 3" />

      {[0, 1].map((i) => (
        <circle key={i} cx={X(hs[i])} cy={Y(vs[i])} r="3.4" fill="#FFFFFF"
          stroke="#A81E12" strokeWidth="1.7" />
      ))}
      <path d={`M${X(168) - 5},${Y(H.forecast168)} l5,-5 l5,5 l-5,5 Z`} fill="#9A5B06" />

      <text x={X(168) + 5} y={Y(H.forecast168) + 3} className="font-mono"
        style={{ fontSize: 8, fill: "#9A5B06", fontWeight: 700 }}>
        {H.forecast168}
      </text>
      <text x={X(168) + 5} y={Y(vs[3]) + 3} className="font-mono"
        style={{ fontSize: 7.5, fill: "#8C939E" }}>
        actual {vs[3]}
      </text>

      {hs.map((t) => (
        <g key={t}>
          <line x1={X(t)} x2={X(t)} y1={y1} y2={y1 + 3} stroke="#9CA2AB" />
          <text x={X(t)} y={y1 + 13} textAnchor="middle" className="font-mono"
            style={{ fontSize: 8, fill: "#8C939E" }}>
            {t}h
          </text>
        </g>
      ))}
      <text x={(x0 + x1) / 2} y={h - 3} textAnchor="middle" className="font-mono"
        style={{ fontSize: 7.5, fill: "#8C939E", letterSpacing: "0.1em" }}>
        SOLID = MEASURED · DASHED AMBER = FORECAST FROM 0 h + 24 h ONLY
      </text>
      <rect x={x0} y={y0} width={x1 - x0} height={y1 - y0} fill="none" stroke="#9CA2AB" />
    </svg>
  );
}

export function ModuleBSection() {
  return (
    <Wrap id="module-b" tone="panel">
      <SectionHead
        index="Module B"
        title="Early drift forecast"
        note="pull the highest-risk components earlier"
      />

      <div className="grid gap-px bg-lab-rule xl:grid-cols-[minmax(0,1.3fr)_minmax(0,1fr)]">
        <div className="bg-lab-card p-5">
          <PanelHead
            title={`Forecasting ${H.serial} from its first 24 hours`}
            meta="the 96 h and 168 h reads are shown faint, for verification only"
            className="-mx-5 -mt-5 mb-4 px-5"
          />
          <ForecastDiagram />
          <ChartNote>
            The model fits V(t) = V₀·(1 + A·(t/168)ⁿ) with one exponent per parameter and solves
            the amplitude per component from the single delta available at hour 24. It never sees
            the 96 h or 168 h reading.
          </ChartNote>
        </div>

        <div className="bg-lab-card p-5">
          <div className="grid grid-cols-2 gap-px bg-lab-hair">
            {[
              { k: "Value @ 0 h", v: `${(H.trace as readonly number[])[0]} ${U}` },
              { k: "Value @ 24 h", v: `${(H.trace as readonly number[])[1]} ${U}` },
              { k: "Predicted @ 168 h", v: `${H.forecast168} ${U}`, tone: "text-sig-amber" },
              { k: "Safety-slope ratio", v: `${H.slopeRatio}×` },
            ].map((f) => (
              <div key={f.k} className="bg-lab-card px-3 py-2.5">
                <div className="label">{f.k}</div>
                <div className={cn("readout mt-1 text-[15px] font-semibold leading-none", f.tone ?? "text-lab-ink")}>
                  {f.v}
                </div>
              </div>
            ))}
          </div>

          <div className="mt-4">
            <div className="label mb-2">Decision rule at hour 24</div>
            <FlowTape
              steps={[
                { k: "Predict", v: "168 h value from 0 h + 24 h" },
                { k: "Bound", v: "0.90 quantile — reject only if even the optimistic case breaches" },
                { k: "Compare", v: "predicted slope vs safety slope" },
                { k: "Act", v: "pull early, or continue the soak" },
              ]}
            />
          </div>

          <div className="mt-4 border-l-[3px] border-l-sig-amber bg-lab-panel px-3.5 py-3">
            <div className="font-mono text-[9.5px] font-bold uppercase tracking-label text-lab-ink">
              What this does and does not claim
            </div>
            <p className="mt-2 font-mono text-[9.5px] leading-relaxed text-lab-dim">
              Module B is an <strong>early triage layer</strong>, not a replacement for the
              complete 168 h screen. The forecast adds little to detection — a forecast is a
              near-monotone function of the early delta, and the starting level carries no defect
              information. What it buys is <strong>time</strong>:{" "}
              <span className="readout font-semibold text-lab-ink">144 oven-hours</span> freed per
              component pulled at hour 24, on the capacity-limiting resource of the whole
              screening line.
            </p>
          </div>
        </div>
      </div>
    </Wrap>
  );
}

/* =====================================================================
 * §8  EXPLAINABILITY
 * ===================================================================== */
export function ExplainSection() {
  const codes = H.codes as readonly { code: string; severity: string; message: string }[];
  const register = LAB.reasons.register as readonly {
    code: string; title: string; gate: string; severity: string; fired: number;
  }[];

  return (
    <Wrap id="explain">
      <SectionHead
        index="04"
        title="Every decision has a reason"
        note={`${LAB.reasons.totalCodes} codes emitted across this screening run`}
      />

      <div className="grid gap-px bg-lab-rule xl:grid-cols-[minmax(0,1fr)_minmax(0,480px)]">
        {/* ------------------------------------------ the inspection record */}
        <div className="bg-lab-card p-5">
          <div className="border-b-2 border-lab-ink pb-2">
            <div className="flex flex-wrap items-baseline justify-between gap-3">
              <span className="font-mono text-[11px] font-bold uppercase tracking-label text-lab-ink">
                Inspection record
              </span>
              <span className="font-mono text-[9px] text-lab-faint">
                model sentinel-0.3.0 · generated UTC
              </span>
            </div>
          </div>

          <div className="mt-3 grid grid-cols-2 gap-px bg-lab-hair sm:grid-cols-4">
            {[
              { k: "Component", v: H.serial },
              { k: "Lot", v: H.lot },
              { k: "Decision", v: H.verdict, tone: "text-sig-red" },
              { k: "Risk score", v: `${H.riskScore} / 100`, tone: "text-sig-red" },
            ].map((f) => (
              <div key={f.k} className="bg-lab-card px-3 py-2">
                <div className="label">{f.k}</div>
                <div className={cn("readout mt-0.5 text-[12px] font-semibold", f.tone ?? "text-lab-ink")}>
                  {f.v}
                </div>
              </div>
            ))}
          </div>

          <div className="mt-4 label">Reason codes</div>
          <ul className="mt-2 space-y-2.5">
            {codes.map((c) => (
              <li key={c.code} className="border border-lab-rule bg-lab-panel px-3.5 py-3">
                <div className="flex flex-wrap items-center gap-2">
                  <span className="readout border border-lab-ink bg-lab-ink px-1.5 py-[2px] text-[10px] font-bold text-lab-panel">
                    {c.code}
                  </span>
                  <SeverityTag s={c.severity} />
                  <span className="font-mono text-[9px] uppercase tracking-label text-lab-dim">
                    {register.find((r) => r.code === c.code)?.title ?? ""}
                  </span>
                </div>
                <p className="mt-2 text-[12px] leading-relaxed text-lab-ink">{c.message}</p>
              </li>
            ))}
          </ul>

          <div className="mt-4 grid grid-cols-2 gap-px bg-lab-hair sm:grid-cols-3">
            {[
              { k: "Observed", v: `${H.value168} ${U}` },
              { k: "Lot median", v: `${H.lotMedian168} ${U}` },
              { k: "Robust deviation", v: `${H.driftZ} σ`, tone: "text-sig-red" },
              { k: "Reference population", v: `lot ${H.lot}, n=${H.lotN}` },
              { k: "Pooled evidence", v: `${H.l3} / 18.5`, tone: "text-sig-red" },
              { k: "Static verdict", v: H.staticVerdict, tone: "text-sig-green" },
            ].map((f) => (
              <div key={f.k} className="bg-lab-card px-3 py-2">
                <div className="label">{f.k}</div>
                <div className={cn("readout mt-0.5 text-[11px] font-semibold", f.tone ?? "text-lab-ink")}>
                  {f.v}
                </div>
              </div>
            ))}
          </div>

          <p className="mt-4 border-l-[3px] border-l-sig-blue bg-lab-panel px-3.5 py-3 font-mono text-[10px] leading-relaxed text-lab-dim">
            The sentence an inspector reads is never &ldquo;the AI considers this component
            risky&rdquo;. It is{" "}
            <span className="text-lab-ink">
              &ldquo;{H.param} drift is {H.driftZ} robust σ above the lot reference&rdquo;
            </span>{" "}
            — a claim with a number, a reference population and a threshold, which an engineer can
            check and, if they disagree, overrule.
          </p>
        </div>

        {/* ---------------------------------------------- the code register */}
        <div className="bg-lab-card p-5">
          <PanelHead
            title="Reason code register"
            meta="rules, not model output"
            className="-mx-5 -mt-5 mb-3 px-5"
          />
          <ul className="divide-y divide-lab-hair">
            {register.map((r) => (
              <li key={r.code} className="py-2.5">
                <div className="flex flex-wrap items-center gap-2">
                  <span className="readout text-[10.5px] font-bold text-lab-ink">{r.code}</span>
                  <span className="font-mono text-[10px] text-lab-dim">{r.title}</span>
                  <span className="ml-auto readout text-[10px] text-lab-faint">
                    {r.fired.toLocaleString()} fired
                  </span>
                </div>
                <div className="mt-1 font-mono text-[8.5px] text-lab-faint">gate: {r.gate}</div>
                <div className="mt-1.5">
                  <Meter
                    value={r.fired}
                    max={Math.max(...register.map((x) => x.fired))}
                    height={4}
                    color={r.severity === "high" ? "#A81E12" : "#9A5B06"}
                  />
                </div>
              </li>
            ))}
          </ul>
          <p className="mt-3 font-mono text-[9px] leading-relaxed text-lab-faint">
            Attribution is <strong>exact, not approximated</strong>. For the robust-z layers the
            contribution to the score <em>is</em> the z-score, and to the pooled score <em>is</em>{" "}
            the squared term. There is no surrogate model between the decision and its
            explanation.
          </p>
          <Link
            href="/console/reports"
            className="mt-4 inline-block border border-lab-ink bg-lab-ink px-3 py-2 font-mono text-[10px] uppercase tracking-label text-lab-panel hover:opacity-85"
          >
            View a full screening report →
          </Link>
        </div>
      </div>
    </Wrap>
  );
}

/* ------------------------------------------------------------ closing */
export function ConsoleCta() {
  return (
    <Wrap tone="panel">
      <div className="grid gap-px bg-lab-rule lg:grid-cols-[minmax(0,1fr)_auto]">
        <div className="bg-lab-card px-5 py-6">
          <h2 className="text-[22px] font-semibold leading-tight tracking-[-0.015em] text-lab-ink">
            The screening console
          </h2>
          <p className="mt-2 max-w-[60ch] text-[13px] leading-relaxed text-lab-dim">
            Lot health against the PDA gate, a component register of all{" "}
            {LAB.headline.parts.toLocaleString()} screened parts, per-component evidence and
            forecast, the decision-policy control, and a printable screening record for any
            component.
          </p>
          <div className="mt-4 grid gap-px bg-lab-rule sm:grid-cols-3 lg:grid-cols-6">
            {[
              ["Overview", "disposition and lot health"],
              ["Screen", "upload a data log, live inference"],
              ["Lots", "distribution, wafer map, PDA"],
              ["Components", "dense register, full detail"],
              ["Analysis", "method and cost policy"],
              ["Reports", "signed inspection record"],
            ].map(([k, v]) => (
              <div key={k} className="bg-lab-card px-2.5 py-2.5">
                <div className="readout text-[10.5px] font-semibold text-lab-ink">{k}</div>
                <div className="mt-1 font-mono text-[8.5px] leading-tight text-lab-faint">{v}</div>
              </div>
            ))}
          </div>
        </div>
        <div className="flex items-center bg-lab-card px-5 py-6">
          <Link
            href="/console"
            className="border border-lab-ink bg-lab-ink px-5 py-3 font-mono text-[12px] uppercase tracking-label text-lab-panel transition-opacity hover:opacity-85"
          >
            Open Screening Console →
          </Link>
        </div>
      </div>
    </Wrap>
  );
}
