"use client";

import { useEffect, useMemo, useState } from "react";
import { Card, CardHead, Notice, PageHead, num } from "@/components/ui/kit";
import { AiSummary } from "@/components/ai/ai-summary";
import { LineChart, Series } from "@/components/realdata/line-chart";
import { Capacitors, EvalScore, Mosfet, realApi } from "@/lib/realdata-api";
import { ApiError } from "@/lib/screen-api";
import { C } from "@/lib/theme";
import { cn } from "@/lib/utils";

/* REAL DATA - NASA aging datasets, prepared for SENTINEL.
 *
 * Every curve here is MEASURED: NASA's readings, reshaped by src/realdata/*
 * (never re-measured, never smoothed). The evaluation asks the early-warning
 * question on real parts and says plainly how few failures it rests on. */

// Stress voltage is an ordered magnitude: one hue, light -> dark.
const VOLT: Record<number, string> = { 10: "#9DC0DD", 12: "#5B92BE", 14: "#2A5C85" };

type Tab = "capacitors" | "mosfet";

export default function RealDataPage() {
  const [tab, setTab] = useState<Tab>("capacitors");
  const [cap, setCap] = useState<Capacitors | null>(null);
  const [mos, setMos] = useState<Mosfet | null>(null);
  const [err, setErr] = useState<Record<Tab, string | null>>({ capacitors: null, mosfet: null });

  useEffect(() => {
    const t = new URLSearchParams(window.location.search).get("set");
    if (t === "mosfet") setTab("mosfet");
    realApi.capacitors().then(setCap).catch((e) =>
      setErr((x) => ({ ...x, capacitors: e instanceof ApiError ? e.message : String(e) })));
    realApi.mosfet().then(setMos).catch((e) =>
      setErr((x) => ({ ...x, mosfet: e instanceof ApiError ? e.message : String(e) })));
  }, []);

  const pick = (t: Tab) => {
    setTab(t);
    window.history.replaceState(null, "", `?set=${t}`);
  };

  return (
    <>
      <PageHead
        title="Real data (NASA)"
        lede="Measured aging data from NASA's Prognostics Center: capacitors under electrical stress and MOSFETs under thermal overstress. Prepared by a script that reshapes the files but never changes a reading, then screened with SENTINEL's methods."
        right={
          <div className="flex overflow-hidden rounded-ctl border border-rule text-sm">
            {(["capacitors", "mosfet"] as Tab[]).map((t) => (
              <button key={t} type="button" onClick={() => pick(t)}
                className={cn("px-3.5 py-2 font-bold", tab === t ? "bg-ink text-sheet" : "bg-sheet text-ink hover:bg-well")}>
                {t === "capacitors" ? "Capacitors" : "MOSFETs"}
              </button>
            ))}
          </div>
        }
      />
      <Notice tone="info" title="Measured, not simulated" className="mb-6">
        Source files are read-only; the prepared copies and the recipe live in <code>data/real/</code> and{" "}
        <code>src/realdata/</code>. Nothing on this page is generated by the digital twin.
      </Notice>

      {tab === "capacitors" ? (
        err.capacitors ? <Missing msg={err.capacitors} /> : cap ? <CapView d={cap} /> : <Loading />
      ) : err.mosfet ? <Missing msg={err.mosfet} /> : mos ? <MosView d={mos} /> : <Loading />}
    </>
  );
}

function Loading() {
  return <p className="text-sm text-graphite">Loading the prepared data…</p>;
}

function Missing({ msg }: { msg: string }) {
  return (
    <Notice tone="warn" title="Not available yet">
      {msg}
    </Notice>
  );
}

function Tile({ k, v, sub }: { k: string; v: string; sub?: string }) {
  return (
    <div className="rounded-card border border-rule bg-sheet px-4 py-3">
      <div className="text-xs text-graphite">{k}</div>
      <div className="wide mt-0.5 text-2xl font-bold tabular-nums">{v}</div>
      {sub && <div className="text-xs text-mute">{sub}</div>}
    </div>
  );
}

function ScoreRow({ name, s }: { name: string; s: EvalScore }) {
  return (
    <tr className="border-b border-hair">
      <td className="py-1.5 pr-2">{name}</td>
      <td className="py-1.5 text-right">{s.failing_later} of {s.parts}</td>
      <td className="py-1.5 text-right">{s.tp} / {s.failing_later}</td>
      <td className="py-1.5 text-right">{s.fp}</td>
      <td className="py-1.5 text-right">{Number.isFinite(s.pr_auc) ? num(s.pr_auc, 2) : "—"}</td>
    </tr>
  );
}

// ================================================================ capacitors
function CapView({ d }: { d: Capacitors }) {
  const [metric, setMetric] = useState<"c" | "esr">("c");
  const eol = new Set(d.truth.filter((t) => t.eol).map((t) => t.serial));
  const series: Series[] = useMemo(() => Object.entries(d.series).map(([id, s]) => ({
    id,
    color: VOLT[s.stress_v] ?? C.cobalt,
    strong: eol.has(id),
    endLabel: eol.has(id) ? `■ ${id}` : undefined,
    points: s.day.map((x, i) => [x, metric === "c" ? s.c_loss_pct[i] : s.esr_rise_pct[i]] as [number, number])
      .filter((p) => Number.isFinite(p[1])),
  })), [d, metric]); // eslint-disable-line react-hooks/exhaustive-deps
  const failed = d.truth.filter((t) => t.eol);
  const days = Math.max(...d.truth.map((t) => t.last_day));
  const ev = d.evaluation;

  return (
    <div className="space-y-5">
      <AiSummary subject={{ context: "realdata", id: "capacitors" }} title="The capacitor data in plain language" />

      <div className="grid grid-cols-2 gap-3 md:grid-cols-4">
        <Tile k="Capacitors" v={String(d.metadata.capacitors)} sub="3 stress voltages, 8 each" />
        <Tile k="Measurements" v={d.metadata.reads.toLocaleString()} sub={`impedance reads over ${days} days`} />
        <Tile k="Reached end of life" v={`${failed.length} of ${d.truth.length}`} sub="all at 14 V" />
        <Tile k="Stress transient" v={`days 0–${d.metadata.conditioning_days}`} sub="flagged, never removed" />
      </div>

      <Card>
        <CardHead
          title={metric === "c" ? "Capacitance loss over the test" : "ESR change over the test"}
          meta="every capacitor, measured; heavy lines reached end of life"
          right={
            <span className="flex overflow-hidden rounded-ctl border border-rule text-xs">
              {([["c", "Capacitance"], ["esr", "ESR"]] as const).map(([k, l]) => (
                <button key={k} type="button" onClick={() => setMetric(k)}
                  className={cn("px-2.5 py-1 font-bold", metric === k ? "bg-ink text-sheet" : "bg-sheet")}>{l}</button>
              ))}
            </span>
          }
        />
        <div className="p-4">
          <LineChart
            series={series}
            xLabel="Day of the stress test"
            yLabel={metric === "c" ? "Capacitance loss from pre-stress (%)" : "ESR change from pre-stress (%)"}
            thresholds={[metric === "c" ? { y: 20, label: "end of life (−20 %)" } : { y: 100, label: "end of life (×2)" }]}
            band={{ x0: 0, x1: d.metadata.conditioning_days, label: "stress transient" }}
            legend={[10, 12, 14].map((v) => ({ label: `${v} V stress`, color: VOLT[v] }))}
            unitY="%"
            ariaLabel={metric === "c" ? "Capacitance loss per capacitor over the test" : "ESR change per capacitor over the test"}
          />
          <p className="mt-2 text-sm text-graphite">
            {metric === "c"
              ? "Capacitance drops sharply when the stress starts, then settles. Only the 14 V capacitors keep losing capacitance; four of them cross the end-of-life line and stay across it."
              : "ESR roughly doubles when the stress starts, then relaxes for the rest of the test - which is why end of life must persist, not just be touched once."}
          </p>
        </div>
      </Card>

      <div className="grid gap-5 xl:grid-cols-2">
        <Card>
          <CardHead title="End-of-life labels" meta="kept apart from the measurements (truth.csv)" />
          <div className="max-h-[420px] overflow-auto">
            <table className="w-full text-sm tabular-nums">
              <thead className="sticky top-0 bg-sheet">
                <tr className="border-b border-rule text-left text-xs text-graphite">
                  <th className="px-4 py-1.5 font-semibold">Capacitor</th>
                  <th className="py-1.5 text-right font-semibold">Stress</th>
                  <th className="py-1.5 text-right font-semibold">C loss at end</th>
                  <th className="py-1.5 text-right font-semibold">ESR at end</th>
                  <th className="px-4 py-1.5 text-right font-semibold">End of life</th>
                </tr>
              </thead>
              <tbody>
                {d.truth.map((t) => (
                  <tr key={t.serial} className={cn("border-b border-hair", t.eol && "bg-reject/5")}>
                    <td className="px-4 py-1.5 font-semibold">{t.serial}</td>
                    <td className="py-1.5 text-right">{t.stress_v} V</td>
                    <td className="py-1.5 text-right">{num(t.c_loss_at_end_pct, 1)} %</td>
                    <td className="py-1.5 text-right">+{num(t.esr_rise_at_end_pct, 1)} %</td>
                    <td className="px-4 py-1.5 text-right">
                      {t.eol ? <span className="font-bold text-reject">■ day {t.eol_day} ({t.eol_by})</span> : <span className="text-graphite">● no</span>}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </Card>

        <Card>
          <CardHead title="Early warning on real parts" meta={ev ? `flag: ${ev.flag_rule}; forecast flags a predicted end-of-test loss >= 20 %` : ""} />
          {!ev ? (
            <p className="p-4 text-sm text-graphite">Not evaluated yet: run <code>python -m src.realdata.evaluate capacitors</code>.</p>
          ) : (
            <div className="space-y-4 p-4">
              {Object.entries(ev.by_read_day).map(([day, r]) => (
                <div key={day}>
                  <p className="text-sm font-bold">At day {day}
                    <span className="ml-2 font-normal text-graphite">
                      excluded as already failed: {r.excluded_already_failed.join(", ") || "none"}
                    </span>
                  </p>
                  <table className="mt-1 w-full text-sm tabular-nums">
                    <thead>
                      <tr className="border-b border-rule text-left text-xs text-graphite">
                        <th className="py-1 font-semibold">Method</th>
                        <th className="py-1 text-right font-semibold">Fail later</th>
                        <th className="py-1 text-right font-semibold">Caught</th>
                        <th className="py-1 text-right font-semibold">False alarms</th>
                        <th className="py-1 text-right font-semibold">PR-AUC</th>
                      </tr>
                    </thead>
                    <tbody>
                      <ScoreRow name="Forecast of end-of-test loss (Module B)" s={r.forecast_end_c_loss} />
                      <ScoreRow name="Pooled drift, whole population (L3 idea)" s={r.pooled_population} />
                      <ScoreRow name="Pooled drift, within stress group" s={r.pooled_within_stress_lot} />
                    </tbody>
                  </table>
                </div>
              ))}
              <Notice tone="warn">
                Only two capacitors fail after the early reads (ES14C4 and ES14C8), so each rate rests on two parts: one
                capacitor moves recall by 50 points. Read this as a check on real data, not a benchmark. Plain accuracy
                is not shown.
              </Notice>
            </div>
          )}
        </Card>
      </div>
    </div>
  );
}

// ==================================================================== mosfet
function MosView({ d }: { d: Mosfet }) {
  const eol = new Set(d.truth.filter((t) => t.eol).map((t) => t.device));
  const byDev = useMemo(() => {
    const m: Record<string, [number, number][]> = {};
    for (const r of d.runs) {
      if (!Number.isFinite(r.rds25_rise_pct)) continue;
      (m[r.device] ??= []).push([r.end_hours, r.rds25_rise_pct]);
    }
    return m;
  }, [d]);
  const series: Series[] = Object.entries(byDev)
    .filter(([, pts]) => pts.length > 1)
    .map(([id, pts]) => ({
      id, color: eol.has(id) ? "#2A5C85" : "#9DC0DD", strong: eol.has(id),
      endLabel: eol.has(id) ? `■ ${id}` : undefined, points: pts.sort((a, b) => a[0] - b[0]),
    }));
  const labelable = d.truth.filter((t) => t.labelable).length;
  const ev = d.evaluation;

  return (
    <div className="space-y-5">
      <AiSummary subject={{ context: "realdata", id: "mosfet" }} title="The MOSFET data in plain language" />
      <div className="grid grid-cols-2 gap-3 md:grid-cols-4">
        <Tile k="Devices" v={String(d.metadata.devices)} sub={`${d.excluded_files} files excluded (listed)`} />
        <Tile k="Switching waveforms" v={d.metadata.waveforms.toLocaleString()} sub="each gives one on-resistance" />
        <Tile k="Can be labelled" v={`${labelable} of ${d.truth.length}`} sub="two or more aging runs" />
        <Tile k="Reached end of life" v={`${eol.size} of ${labelable}`} sub="Rds(on) +20 %, persisting" />
      </div>
      <Card>
        <CardHead title="On-resistance at 25 °C, per device, across its aging runs"
          meta="temperature-corrected; one point per run (median of its waveforms)" />
        <div className="p-4">
          {series.length ? (
            <LineChart series={series} xLabel="Hours of thermal overstress" yLabel="Rds(on) change from first run (%)"
              thresholds={[{ y: 20, label: "end of life (+20 %)" }]}
              legend={[{ label: "reached end of life", color: "#2A5C85" }, { label: "other devices", color: "#9DC0DD" }]}
              unitY="%" fmtX={(v) => v.toFixed(0)} ariaLabel="On-resistance change per MOSFET over aging" />
          ) : (
            <p className="text-sm text-graphite">No device has more than one run to draw.</p>
          )}
          <p className="mt-2 text-sm text-graphite">
            The tests do not all use the same MOSFET type, so each device is compared with its own first run rather
            than with the others.
          </p>
        </div>
      </Card>
      <div className="grid gap-5 xl:grid-cols-2">
        <Card>
          <CardHead title="Devices" meta="labels in truth.csv" />
          <div className="max-h-[420px] overflow-auto">
            <table className="w-full text-sm tabular-nums">
              <thead className="sticky top-0 bg-sheet">
                <tr className="border-b border-rule text-left text-xs text-graphite">
                  <th className="px-4 py-1.5 font-semibold">Device</th>
                  <th className="py-1.5 text-right font-semibold">Runs</th>
                  <th className="py-1.5 text-right font-semibold">Hours</th>
                  <th className="py-1.5 text-right font-semibold">Rds(on) change</th>
                  <th className="px-4 py-1.5 text-right font-semibold">End of life</th>
                </tr>
              </thead>
              <tbody>
                {d.truth.map((t) => (
                  <tr key={t.device} className={cn("border-b border-hair", t.eol && "bg-reject/5")}>
                    <td className="px-4 py-1.5 font-semibold">{t.device}</td>
                    <td className="py-1.5 text-right">{t.runs}</td>
                    <td className="py-1.5 text-right">{num(t.hours, 1)}</td>
                    <td className="py-1.5 text-right">{t.rds25_rise_pct >= 0 ? "+" : ""}{num(t.rds25_rise_pct, 1)} %</td>
                    <td className="px-4 py-1.5 text-right">
                      {!t.labelable ? <span className="text-mute">— one run only</span>
                        : t.eol ? <span className="font-bold text-reject">■ run {t.eol_run} ({num(t.eol_hours ?? 0, 1)} h)</span>
                        : <span className="text-graphite">● no</span>}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </Card>
        <Card>
          <CardHead title="Early warning on real devices" meta={ev?.early_read ?? ""} />
          <div className="p-4 text-sm">
            {!ev || !ev.pooled_population ? (
              <p className="text-graphite">{ev?.note ?? "Not evaluated yet: run python -m src.realdata.evaluate mosfet."}</p>
            ) : (
              <>
                <p>
                  Scored {ev.devices_scored} devices not yet failed at the early read; {ev.pooled_population.failing_later} fail
                  later. Caught {ev.pooled_population.tp} of them with {ev.pooled_population.fp} false alarm
                  {ev.pooled_population.fp === 1 ? "" : "s"} (PR-AUC {Number.isFinite(ev.pooled_population.pr_auc) ? num(ev.pooled_population.pr_auc, 2) : "—"}).
                </p>
                <table className="mt-3 w-full tabular-nums">
                  <thead>
                    <tr className="border-b border-rule text-left text-xs text-graphite">
                      <th className="py-1 font-semibold">Highest early score</th>
                      <th className="py-1 text-right font-semibold">Pooled z</th>
                      <th className="py-1 text-right font-semibold">Rds(on) change</th>
                      <th className="py-1 text-right font-semibold">Fails later</th>
                    </tr>
                  </thead>
                  <tbody>
                    {(ev.ranking ?? []).map((r) => (
                      <tr key={r.device} className="border-b border-hair">
                        <td className="py-1">{r.device}</td>
                        <td className="py-1 text-right">{num(r.pooled_z, 2)}</td>
                        <td className="py-1 text-right">{num(r.rds_rise_pct, 1)} %</td>
                        <td className="py-1 text-right">{r.fails_later ? "■ yes" : "● no"}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </>
            )}
            <p className="mt-3 text-xs text-graphite">
              Early read = the end of each device&apos;s first run (its last 10 % of waveforms against its first 10 %).
              With 13 of 21 devices failing later, chance alone gives a PR-AUC near 0.62, so this early signal is weak;
              the threshold-voltage estimate is noisy and dominates some scores. Latch-up is not used as a label: in
              these files the current channel reads 0.2–0.3 A with the gate off, even on healthy devices.
            </p>
          </div>
        </Card>
      </div>
    </div>
  );
}

