"""Adapter for SENTINEL's own wide burn-in format.

The reference implementation of `DatasetAdapter`. It exists for two reasons
beyond tidiness: it proves the normalized schema can round-trip the native
format without loss, and it gives an author of a NASA or tester adapter a
worked example to copy rather than a docstring to interpret.

It is also the honest baseline for `equivalent_to_burn_in=True` - the only
adapter entitled to set that flag, because it IS the burn-in data.
"""

from __future__ import annotations

import pandas as pd

from src.features import LOT_COL, PARAM_NAMES, PARAMS, TIMEPOINTS

from backend.app.adapters.base import (
    AdapterResult, DatasetAdapter, MeasurementRecord, SourceProvenance,
    registry, to_long_frame,
)

__all__ = ["SentinelCsvAdapter", "wide_from_long"]


class SentinelCsvAdapter(DatasetAdapter):
    name = "sentinel-burnin-csv"

    provenance = SourceProvenance(
        source_dataset="sentinel-synthetic-burnin",
        source_device_type="CMOS ASIC (simulated)",
        source_stress_condition="static burn-in, 125 C, 168 h, MIL-STD-883 M1015",
        equivalent_to_burn_in=True,
        notes=("The native format. Generated by src/generate_burnin_dataset.py "
               "at seed 42; all values are simulated."),
    )

    def validate(self, raw: pd.DataFrame) -> list[str]:
        problems = []
        for c in ("serial", LOT_COL):
            if c not in raw.columns:
                problems.append(f"missing identifier column {c!r}")
        if not any(f"{p}_0h" in raw.columns for p in PARAM_NAMES):
            problems.append("no recognisable {PARAMETER}_0h measurement columns")
        return problems

    def map_parameters(self) -> dict:
        return {p: {"canonical": p, "unit": PARAMS[p]["unit"],
                    "usl": PARAMS[p]["usl"], "label": PARAMS[p]["label"]}
                for p in PARAM_NAMES}

    def map_timepoints(self, raw: pd.DataFrame) -> dict:
        """Column suffix to elapsed stress hours. Only points actually present."""
        return {f"_{t}h": float(t) for t in TIMEPOINTS
                if any(f"{p}_{t}h" in raw.columns for p in PARAM_NAMES)}

    def normalize(self, raw: pd.DataFrame) -> AdapterResult:
        records: list[MeasurementRecord] = []
        warnings: list[str] = []
        times = self.map_timepoints(raw)

        for _, row in raw.iterrows():
            for p in PARAM_NAMES:
                for suffix, hours in times.items():
                    col = f"{p}{suffix}"
                    if col not in raw.columns:
                        continue
                    v = row[col]
                    # A dropped handler read stays absent. Emitting a row with a
                    # null value would be a measurement that never happened.
                    if pd.isna(v):
                        continue
                    records.append(MeasurementRecord(
                        serial=str(row["serial"]),
                        lot=str(row[LOT_COL]),
                        parameter=p,
                        time_hours=hours,
                        value=float(v),
                        unit=PARAMS[p]["unit"],
                        source=self.provenance.source_dataset,
                        device_type=self.provenance.source_device_type,
                        stress_condition=self.provenance.source_stress_condition,
                        # No per-component thermal telemetry exists in this
                        # dataset. The chamber set point is 125 C, but that is
                        # a process parameter, not a measurement of this part,
                        # and recording it here would fabricate one.
                        temperature_c=None,
                        voltage_v=None,
                    ))

        if not records:
            warnings.append("no measurements were normalised; check the columns")

        return AdapterResult(
            long=to_long_frame(records),
            provenance=self.provenance,
            parameter_map=self.map_parameters(),
            timepoint_map=times,
            warnings=warnings,
        )


registry[SentinelCsvAdapter.name] = SentinelCsvAdapter


def wide_from_long(long: pd.DataFrame,
                   read_points: list[float] | None = None) -> pd.DataFrame:
    """Pivot a normalized long frame back to the wide schema the pipeline reads.

    Only emits a `{PARAM}_{T}h` column where that (parameter, time) pair was
    actually measured, so a foreign dataset with a different cadence produces a
    frame the validator can honestly reject rather than a dense grid of
    invented values.
    """
    if long.empty:
        return pd.DataFrame(columns=["serial", LOT_COL])

    times = (sorted(float(t) for t in long["time_hours"].unique())
             if read_points is None else read_points)
    ids = (long[["serial", "lot"]].drop_duplicates()
           .rename(columns={"lot": LOT_COL}).reset_index(drop=True))

    out = ids
    for p in sorted(long["parameter"].unique()):
        for t in times:
            sel = long[(long["parameter"] == p) & (long["time_hours"] == t)]
            if sel.empty:
                continue
            col = f"{p}_{int(t)}h"
            out = out.merge(
                sel[["serial", "value"]].rename(columns={"value": col}),
                on="serial", how="left")
    return out
